name: infinit_flutter
description:
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.2.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.0

flutter:
  uses-material-design: true
